---
# SPDX-FileCopyrightText: 2024 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.3.2
    hooks:
      - id: prettier

  - repo: https://github.com/rivosinc/reuse-tool
    rev: "092e17c7287dad33a3da7fde22185dea29698810"
    hooks:
      # Check compliance
      - id: reuse

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.27
    hooks:
      - id: actionlint
        files: ^workflow-templates/
